name: Run Data Automation Scripts

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # This runs every hour

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Include all your dependencies in requirements.txt

    - name: Run Retail Consumption
      run: |
        python "./code/retailConsumption.py"
        
    - name: Run 24h Volatility & Trading Range
      run: |
        python "./code/24h Volatility & Trading Range.py"

    - name: Run CoinDesk Sentiment
      run: |
        python "./code/CoinDeskSentiment.py"

    - name: Run Consumer Confidence
      run: |
        python "./code/ConsumerConfidence.py"

    - name: Run Currency Exchange
      run: |
        python "./code/CurrencyExchange.py"

    - name: Run GDP Data
      run: |
        python "./code/GDPData.py"

    - name: Run Global GDP
      run: |
        python "./code/GlobalGDP.py"

    - name: Run Google Trending
      run: |
        python "./code/GoogleTrending.py"

    - name: Run Inflation Data
      run: |
        python "./code/InflationData.py"

    - name: Run Interest Rate
      run: |
        python "./code/InterestRate.py"

    - name: Run Market Cap
      run: |
        python "./code/MarketCap.py"

    - name: Run Prices Script
      run: |
        python "./code/PricesScript.py"

    - name: Run Unemployment Data
      run: |
        python "./code/UnemploymentData.py"

    - name: Run Volume Traded
      run: |
        python "./code/VolumeTraded.py"

    
