name: Run All Data Scripts Hourly

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

jobs:
  run-data-scripts:
    runs-on: ubuntu-latest

    env:
      DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
      FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
      AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run "USDollarIndex.pyy"
        run: python "./code/USDollarIndex.py"
        
      - name: Run "SPYData.py"
        run: python "./code/SPYData.py"
        
      - name: Run "QQQData.py"
        run: python "./code/QQQData.py"
        
      - name: Run "BTCPriceDaily.pyy"
        run: python "./code/BTCPriceDaily.py"
        
      - name: Run "GoldDailyPrice.py"
        run: python "./code/GoldDailyPrice.py"
        
      - name: Run "24h Volatility & Trading Range.py"
        run: python "./code/24h Volatility & Trading Range.py"

      - name: Run CoinDeskSentiment.py
        run: python "./code/CoinDeskSentiment.py"

      - name: Run ConsumerConfidence.py
        run: python "./code/ConsumerConfidence.py"

      - name: Run CurrencyExchange.py
        run: python "./code/CurrencyExchange.py"

      - name: Run GDPData.py
        run: python "./code/GDPData.py"

      - name: Run GlobalGDP.py
        run: python "./code/GlobalGDP.py"

      - name: Run GoogleTrending.py
        run: python "./code/GoogleTrending.py"

      - name: Run InflationData.py
        run: python "./code/InflationData.py"

      - name: Run InterestRate.py
        run: python "./code/InterestRate.py"

      - name: Run MarketCap.py
        run: python "./code/MarketCap.py"

      - name: Run PricesScript.py
        run: python "./code/PricesScript.py"

      - name: Run UnemploymentData.py
        run: python "./code/UnemploymentData.py"

      - name: Run VolumeTraded.py
        run: python "./code/VolumeTraded.py"

      - name: Run retailConsumption.py
        run: python "./code/retailConsumption.py"
