name: Run Data Automation Scripts

# Trigger this workflow on push to main, manually, or on a scheduled basis
on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggers
  schedule:
    # Run every hour
    - cron: '0 * * * *'  # This runs the workflow at the start of every hour

jobs:
  run-scripts:
    runs-on: ubuntu-latest  # You can use other runners like 'windows-latest' or 'macos-latest'

    steps:
    # Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Change to your desired version

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Make sure to include all the necessary dependencies in requirements.txt

    # Run the scripts in parallel or sequentially
    - name: Run data automation scripts
      run: |
        # Install any additional tools if necessary
        pip install pycoingecko  # Example of required package, modify accordingly
        python run_all.py  # Make sure you have the run_all.py script ready in your repository
